spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: dbflarla496695@gmail.com
    password: taqtdprezcpptusl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

auth:
  jwt:
    secret-key: 12341234123412341234123412341234123412341234123412341234123412341234123412341234